export const CONSTANTS = Object.freeze({
  productName: '상품명',
  price: '가격',
  quantity: '수량',
  addProduct: '상품 추가하기',
  add: '추가하기',
  productStatus: '상품 현황',
  insertCoin: '금액 투입',
  insert: '투입',
  amountInserted: '투입한 금액: ',
  availableProductStatus: '구매할 수 있는 상품 현황',
  purchase: '구매',
  purchaseButtonText: '구매하기',
  change: '잔돈',
  return: '반환하기',
  coin: '동전',
  coinQuantityHeader: '개수',
  coinQuantityRow: '개',
  chargeVendingMachine: '자판기 동전 충전하기',
  charge: '충전하기',
  holdingAmount: '보유 금액: ',
  holdingCoinStatus: '동전 보유 현황',
});
